# Reset index practice

In [1]:
import pandas as pd 
import numpy as np

In [2]:
url = "https://www.pikminwiki.com/Piklopedia_(Pikmin_4)"

In [3]:
df = pd.read_html(url)

In [4]:
for index, i in enumerate(df):
    print(f'index = {index} {i}')

index = 0                                                    0
0  The following article or section is in need of...
index = 1        #  Icon                   Name                      Scientific name  \
0      1   NaN          Dwarf Bulborb         Pansarus pseudooculii russus
1      2   NaN   Albino Dwarf Bulborb    Oculus kageyamii larva (1st molt)
2      3   NaN                Bulborb              Oculus kageyamii russus
3      4   NaN          Jumbo Bulborb  Oculus kageyamii russus (polyploid)
4      5   NaN   Dwarf Orange Bulborb       Pansarus pseudooculii orangium
..   ...   ...                    ...                                  ...
120  121   NaN           Candypop Bud                       Flora expellus
121  122   NaN            Pellet Posy                        Amplus nutrio
122  123   NaN  Burgeoning Spiderwort             Pikflora baccae conditus
123  124   NaN            Glow Pikmin                Pikminidae supravelum
124  125   NaN              Lumiknoll                     Collux aeternium

          Family Active During Weight Max. carriers Sparklium value Seeds  \
0       Breadbug           day      3             6               3     3
1       Grub-Dog         night      3             6               3     3
2       Grub-Dog     day/night     10            20              10    10
3       Grub-Dog     day/night     20            40              15    15
4       Breadbug           day      3             6               3     3
..           ...           ...    ...           ...             ...   ...
120     Candypop           day      -             -             NaN     -
121  Pellet Weed           day   1-10          2-20             NaN  1-10
122  Pellet Weed           day      1             1             NaN     -
123          ???         night      1             -               -     -
124          ???         night      -             -               -     -

                                                 Notes
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
120                                                NaN
121                                                NaN
122  Must have collected 10 berries (1 Ultra-spicy ...
123                                                NaN
124                                                NaN

[125 rows x 11 columns]
index = 2                 Language                  Name                Meaning
0               Japanese  生物図鑑? Seibutsu Zukan   Creature Field Guide
1  Chinese (traditional)   生物圖鑑 Shēngwù Tújiàn  Organism Picture Book
2   Chinese (simplified)   生物图鉴 Shēngwù Tújiàn  Organism Picture Book
3                  Dutch            Piklopedia                      -
4                 French            Piklopédie                      -
5                 German            Piklopädie                      -
6                Italian            Piklopedia                      -
7                 Korean  생물 도감 Saengmul Dogam  Organism Picture Book
8             Portuguese            Piklopédia                      -
9                Spanish            Piklopedia                      -

In [5]:
df = df[1]

In [6]:
df

,#,Icon,Name,Scientific name,Family,Active During,Weight,Max. carriers,Sparklium value,Seeds,Notes
0,1,NaN,Dwarf Bulborb,Pansarus pseudooculii russus,Breadbug,day,3,6,3,3,NaN
1,2,NaN,Albino Dwarf Bulborb,Oculus kageyamii larva (1st molt),Grub-Dog,night,3,6,3,3,NaN
2,3,NaN,Bulborb,Oculus kageyamii russus,Grub-Dog,day/night,10,20,10,10,NaN
3,4,NaN,Jumbo Bulborb,Oculus kageyamii russus (polyploid),Grub-Dog,day/night,20,40,15,15,NaN
4,5,NaN,Dwarf Orange Bulborb,Pansarus pseudooculii orangium,Breadbug,day,3,6,3,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...
120,121,NaN,Candypop Bud,Flora expellus,Candypop,day,-,-,NaN,-,NaN
121,122,NaN,Pellet Posy,Amplus nutrio,Pellet Weed,day,1-10,2-20,NaN,1-10,NaN
122,123,NaN,Burgeoning Spiderwort,Pikflora baccae conditus,Pellet Weed,day,1,1,NaN,-,Must have collected 10 berries (1 Ultra-spicy ...
123,124,NaN,Glow Pikmin,Pikminidae supravelum,???,night,1,-,-,-,NaN
124,125,NaN,Lumiknoll,Collux aeternium,???,night,-,-,-,-,NaN

### Question 1: Delete any number of rows using .drop.

In [28]:
#Interesting this is how to do a slice of indexes whe dropping

,#,Icon,Name,Scientific name,Family,Active During,Weight,Max. carriers,Sparklium value,Seeds,Notes
19,20,NaN,Titan Blowhog,Sus draconus (hypertrophic),Blowhog,day,15,30,15,15,NaN
20,21,NaN,Blizzarding Blowhog,Sus nivisventis (hypertrophic),Blowhog,day,15,30,15,15,NaN
21,22,NaN,Tusked Blowhog,Sus magdentum,Tusked Blowhog,day/night,7,14,7,6,NaN
22,23,NaN,Armored Cannon Larva,Granitus chukkulinae (larva),Lithopod,day,7,14,7,8,Has to be agitated to be discovered.
23,24,NaN,Horned Cannon Beetle,Granitus ferrous,Lithopod,day,30,60,20,50,NaN
...,...,...,...,...,...,...,...,...,...,...,...
120,121,NaN,Candypop Bud,Flora expellus,Candypop,day,-,-,NaN,-,NaN
121,122,NaN,Pellet Posy,Amplus nutrio,Pellet Weed,day,1-10,2-20,NaN,1-10,NaN
122,123,NaN,Burgeoning Spiderwort,Pikflora baccae conditus,Pellet Weed,day,1,1,NaN,-,Must have collected 10 berries (1 Ultra-spicy ...
123,124,NaN,Glow Pikmin,Pikminidae supravelum,???,night,1,-,-,-,NaN
124,125,NaN,Lumiknoll,Collux aeternium,???,night,-,-,-,-,NaN

### Question 2: Reset the index in a new dataframe called df2

,index,#,Icon,Name,Scientific name,Family,Active During,Weight,Max. carriers,Sparklium value,Seeds,Notes
0,19,20,NaN,Titan Blowhog,Sus draconus (hypertrophic),Blowhog,day,15,30,15,15,NaN
1,20,21,NaN,Blizzarding Blowhog,Sus nivisventis (hypertrophic),Blowhog,day,15,30,15,15,NaN
2,21,22,NaN,Tusked Blowhog,Sus magdentum,Tusked Blowhog,day/night,7,14,7,6,NaN
3,22,23,NaN,Armored Cannon Larva,Granitus chukkulinae (larva),Lithopod,day,7,14,7,8,Has to be agitated to be discovered.
4,23,24,NaN,Horned Cannon Beetle,Granitus ferrous,Lithopod,day,30,60,20,50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
101,120,121,NaN,Candypop Bud,Flora expellus,Candypop,day,-,-,NaN,-,NaN
102,121,122,NaN,Pellet Posy,Amplus nutrio,Pellet Weed,day,1-10,2-20,NaN,1-10,NaN
103,122,123,NaN,Burgeoning Spiderwort,Pikflora baccae conditus,Pellet Weed,day,1,1,NaN,-,Must have collected 10 berries (1 Ultra-spicy ...
104,123,124,NaN,Glow Pikmin,Pikminidae supravelum,???,night,1,-,-,-,NaN
105,124,125,NaN,Lumiknoll,Collux aeternium,???,night,-,-,-,-,NaN

### Question 3: Reset the index of the original df in a new df called df3, but make sure the original index is deleted from the new dataframe

,#,Icon,Name,Scientific name,Family,Active During,Weight,Max. carriers,Sparklium value,Seeds,Notes
0,20,NaN,Titan Blowhog,Sus draconus (hypertrophic),Blowhog,day,15,30,15,15,NaN
1,21,NaN,Blizzarding Blowhog,Sus nivisventis (hypertrophic),Blowhog,day,15,30,15,15,NaN
2,22,NaN,Tusked Blowhog,Sus magdentum,Tusked Blowhog,day/night,7,14,7,6,NaN
3,23,NaN,Armored Cannon Larva,Granitus chukkulinae (larva),Lithopod,day,7,14,7,8,Has to be agitated to be discovered.
4,24,NaN,Horned Cannon Beetle,Granitus ferrous,Lithopod,day,30,60,20,50,NaN
...,...,...,...,...,...,...,...,...,...,...,...
101,121,NaN,Candypop Bud,Flora expellus,Candypop,day,-,-,NaN,-,NaN
102,122,NaN,Pellet Posy,Amplus nutrio,Pellet Weed,day,1-10,2-20,NaN,1-10,NaN
103,123,NaN,Burgeoning Spiderwort,Pikflora baccae conditus,Pellet Weed,day,1,1,NaN,-,Must have collected 10 berries (1 Ultra-spicy ...
104,124,NaN,Glow Pikmin,Pikminidae supravelum,???,night,1,-,-,-,NaN
105,125,NaN,Lumiknoll,Collux aeternium,???,night,-,-,-,-,NaN

### Question 4: Edit the original dataframe by first copying  as df4, and then reseting the copy's index without putting it in a new variable.

In [22]:
df4 = df.copy()

,index,#,Icon,Name,Scientific name,Family,Active During,Weight,Max. carriers,Sparklium value,Seeds,Notes
0,19,20,NaN,Titan Blowhog,Sus draconus (hypertrophic),Blowhog,day,15,30,15,15,NaN
1,20,21,NaN,Blizzarding Blowhog,Sus nivisventis (hypertrophic),Blowhog,day,15,30,15,15,NaN
2,21,22,NaN,Tusked Blowhog,Sus magdentum,Tusked Blowhog,day/night,7,14,7,6,NaN
3,22,23,NaN,Armored Cannon Larva,Granitus chukkulinae (larva),Lithopod,day,7,14,7,8,Has to be agitated to be discovered.
4,23,24,NaN,Horned Cannon Beetle,Granitus ferrous,Lithopod,day,30,60,20,50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
101,120,121,NaN,Candypop Bud,Flora expellus,Candypop,day,-,-,NaN,-,NaN
102,121,122,NaN,Pellet Posy,Amplus nutrio,Pellet Weed,day,1-10,2-20,NaN,1-10,NaN
103,122,123,NaN,Burgeoning Spiderwort,Pikflora baccae conditus,Pellet Weed,day,1,1,NaN,-,Must have collected 10 berries (1 Ultra-spicy ...
104,123,124,NaN,Glow Pikmin,Pikminidae supravelum,???,night,1,-,-,-,NaN
105,124,125,NaN,Lumiknoll,Collux aeternium,???,night,-,-,-,-,NaN

### Question 5: Edit the original dataframe by first copying  as df5, then reset the copy's index without putting it in a new variable and make sure it does the original index is not stored in df5

In [25]:
df5 = df.copy()

,#,Icon,Name,Scientific name,Family,Active During,Weight,Max. carriers,Sparklium value,Seeds,Notes
0,20,NaN,Titan Blowhog,Sus draconus (hypertrophic),Blowhog,day,15,30,15,15,NaN
1,21,NaN,Blizzarding Blowhog,Sus nivisventis (hypertrophic),Blowhog,day,15,30,15,15,NaN
2,22,NaN,Tusked Blowhog,Sus magdentum,Tusked Blowhog,day/night,7,14,7,6,NaN
3,23,NaN,Armored Cannon Larva,Granitus chukkulinae (larva),Lithopod,day,7,14,7,8,Has to be agitated to be discovered.
4,24,NaN,Horned Cannon Beetle,Granitus ferrous,Lithopod,day,30,60,20,50,NaN
...,...,...,...,...,...,...,...,...,...,...,...
101,121,NaN,Candypop Bud,Flora expellus,Candypop,day,-,-,NaN,-,NaN
102,122,NaN,Pellet Posy,Amplus nutrio,Pellet Weed,day,1-10,2-20,NaN,1-10,NaN
103,123,NaN,Burgeoning Spiderwort,Pikflora baccae conditus,Pellet Weed,day,1,1,NaN,-,Must have collected 10 berries (1 Ultra-spicy ...
104,124,NaN,Glow Pikmin,Pikminidae supravelum,???,night,1,-,-,-,NaN
105,125,NaN,Lumiknoll,Collux aeternium,???,night,-,-,-,-,NaN